# Generated by Django 4.0.4 on 2022-05-27 16:20

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_account_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('logo', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('max_numbers_of_teams', models.PositiveIntegerField()),
                ('rank', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.account')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.CharField(blank=True, max_length=200, null=True)),
                ('coach', models.CharField(max_length=100, unique=True)),
                ('max_numbers_of_players', models.PositiveIntegerField()),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.account')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.account')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.team')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=5, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('point', models.FloatField(blank=True, null=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.account')),
            ],
        ),
    ]
