# Generated by Django 4.0.4 on 2022-05-27 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_season_team_seasondetail_player'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SeasonDetail',
            new_name='Season_Detail',
        ),
    ]
