# Generated by Django 4.0.4 on 2022-05-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_rename_seasondetail_season_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='logo',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
