# Generated by Django 4.0.4 on 2022-05-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_season_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='logo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
